openapi: 3.0.0
info:
  title: JIRA API Mockup
  description: API documentation for the JIRA API Mockup
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
paths:
  /issues:
    get:
      summary: Get all issues
      responses:
        '200':
          description: A list of issues
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    description:
                      type: string
                    status:
                      type: string
                    assignee:
                      type: string
                    project_key:
                      type: string
                    type:
                      type: string
    post:
      summary: Create a new issue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                status:
                  type: string
                assignee:
                  type: string
                project_key:
                  type: string
                type:
                  type: string
      responses:
        '201':
          description: Issue created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  status:
                    type: string
                  assignee:
                    type: string
                  project_key:
                    type: string
                  type:
                    type: string
  /issues/{issue_id}:
    get:
      summary: Get issue by ID
      parameters:
        - in: path
          name: issue_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Issue details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  status:
                    type: string
                  assignee:
                    type: string
                  project_key:
                    type: string
                  type:
                    type: string
        '404':
          description: Issue not found
    put:
      summary: Update issue by ID
      parameters:
        - in: path
          name: issue_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                status:
                  type: string
                assignee:
                  type: string
                project_key:
                  type: string
                type:
                  type: string
      responses:
        '200':
          description: Issue updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  status:
                    type: string
                  assignee:
                    type: string
                  project_key:
                    type: string
                  type:
                    type: string
        '404':
          description: Issue not found
    delete:
      summary: Delete issue by ID
      parameters:
        - in: path
          name: issue_id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Issue deleted
        '404':
          description: Issue not found
  /projects:
    get:
      summary: Get all projects
      responses:
        '200':
          description: A list of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    key:
                      type: string
                    name:
                      type: string
                    teams:
                      type: object
                      additionalProperties:
                        type: array
                        items:
                          type: string
  /owners:
    get:
      summary: Get all owners
      responses:
        '200':
          description: A list of owners
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /issue_types:
    get:
      summary: Get all issue types
      responses:
        '200':
          description: A list of issue types
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /subtypes:
    get:
      summary: Get all subtypes
      responses:
        '200':
          description: A list of subtypes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /projects/{project_key}/teams:
    post:
      summary: Add a team to a project
      parameters:
        - in: path
          name: project_key
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                team_name:
                  type: string
                team_members:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Team added to project
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
                  name:
                    type: string
                  teams:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
        '404':
          description: Project not found